help :-
        write('#####################################################################'), nl,
        write('# Game Guide                                                        #'), nl,
        write('# ================================================================= #'), nl,
        write('#                                                                   #'), nl,
        write('# I. How to Play                                                    #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# 1. Game dimulai dengan mengetikan "main_menu."                    #'), nl,
        write('# 2. Cara untuk bermain adalah dengan mengetikan command / pilihan  #'), nl,
        write('#    dalam game ini dengan bahasa prolog.                           #'), nl,
        write('# 3. Setiap command selalu diakhiri dengan tanda titik (.)          #'), nl,
        write('# 4. Misi utama dari game ini adalah untuk mengalahkan Bos Akhir    #'), nl,
        write('# 5. Terdapat side-quest untuk menambah gold / exp                  #'), nl,
        write('#                                                                   #'), nl,
        write('# II. List Command In-Game                                          #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# 1. start           : untuk memulai petualanganmu                  #'), nl,
        write('# 2. help            : menampilkan segala bantuan                   #'), nl,
        write('# 3. map             : menampilkan peta                             #'), nl,
        write('# 4. condition       : menampilkan kondisi pemain terkini           #'), nl,
        write('# 5. stats           : menampilkan status pemain                    #'), nl,
        write('# 6. rucksack        : menampilkan inventory pemain                 #'), nl,
        write('# 7. shop            : mengunjungi shop                             #'), nl,
        write('#                                                                   #'), nl,
        write('# III. List Command Menu                                            #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# 1. main_Menu       : menampilkan menu awal game                   #'), nl,
        write('# 2. game_Menu       : menampilkan menu in-game                     #'), nl,
        write('# 3. shop_Menu       : menampilkan menu shop                        #'), nl,
        write('#                                                                   #'), nl,
        write('# IV. List Command Shop                                             #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# 1. gacha          : membeli equipment dengan sistem gacha         #'), nl,
        write('# 2. potion         : membeli potion                                #'), nl,
        write('# 3. ether          : membeli ether                                 #'), nl,
        write('# 4. antidote       : membeli antidote                              #'), nl,
        write('# 5. antiparalyze   : membeli antiparalyze                          #'), nl,
        write('# 6. x-Attack       : membeli x-attack                              #'), nl,
        write('# 7. x-Defense      : membeli x-defense                             #'), nl,
        write('# 8. exitShop                                                       #'), nl,
        write('#                                                                   #'), nl,
        write('# V. List Command Movement                                          #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# w                 : gerak ke utara 1 langkah                      #'), nl,
        write('# s                 : gerak ke selatan 1 langkah                    #'), nl,
        write('# d                 : gerak ke ke timur 1 langkah                   #'), nl,
        write('# a                 : gerak ke barat 1 langkah                      #'), nl,
        write('#                                                                   #'), nl,
        write('# VI. Simbol - simbol dalam map                                     #'), nl,
        write('# ----------------------------------------------------------------- #'), nl,
        write('# P                 : Posisi pemain utama                           #'), nl,
        write('# #                 : Batas dari map                                #'), nl,
        write('# S                 : Lokasi dari shop / store                      #'), nl,
        write('# D                 : Bos Akhir / Boss Dungeon                      #'), nl,
        write('# Q                 : Lokasi Side-quest                             #'), nl,
        write('#####################################################################'), nl.