/* fakta pemain */
:- dynamic(job/1).
:- dynamic(att/1).
:- dynamic(specialatt/2). % parameter 1 buat jumlah damage, parameter 2 buat cooldown
:- dynamic(def/1).
:- dynamic(currHP/1).
:- dynamic(maxHP/1).
:- dynamic(expr/1).
:- dynamic(gold/1).
:- dynamic(lvl/1).
:- dynamic(startstate/1).

startstate(0).

start :- 
        startstate(State),
        State is 0,
        write('Choose your job: '), nl,
        write('1. Swordsman'), nl,
        write('2. Sorcerer'), nl,
        write('3. Archer'), nl,
        write('Input your job number'), nl,
        retract(startstate(_)),
        asserta(startstate(1)),
        read(InputJob), 
        assignJob(InputJob),!.
start :-
        startstate(State),
        State is 1,
        write('The game has already started, do not try to cheat!'),!.

assignJob(InputJob) :- 
        InputJob = 1, 
        retractall(job(_)),
        asserta(job(swordsman)),
        asserta(usedSpace(0)),
        asserta(isOnQuest(0)),
        asserta(jmlGoblin(0)),
        asserta(jmlSlime(0)),
        asserta(jmlWolf(0)),
        asserta(jmlWitch(0)),
        asserta(jmlArmoredGoblin(0)),
        asserta(jmlCubicSlime(0)),
        asserta(jmlWerewolf(0)),
        asserta(jmlOgre(0)),
        asserta(jmlCursedKnight(0)),
        asserta(jmlUltimaDragon(0)),
        asserta(rewardExp(0)),
        asserta(rewardGold(0)),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        asserta(weaponEquipped(longsword)),
        asserta(armorEquipped(none)),
        asserta(accessoryEquipped(none)),
        write('Your Job is Swordsman'), inputStats(swordsman), !.
assignJob(InputJob) :- 
        InputJob = 2, 
        retractall(job(_)),
        asserta(job(sorcerer)),
        asserta(usedSpace(0)),
        asserta(isOnQuest(0)),
        asserta(jmlGoblin(0)),
        asserta(jmlSlime(0)),
        asserta(jmlWolf(0)),
        asserta(jmlWitch(0)),
        asserta(jmlArmoredGoblin(0)),
        asserta(jmlCubicSlime(0)),
        asserta(jmlWerewolf(0)),
        asserta(jmlOgre(0)),
        asserta(jmlCursedKnight(0)),
        asserta(jmlUltimaDragon(0)),
        asserta(rewardExp(0)),
        asserta(rewardGold(0)),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        asserta(weaponEquipped(magestaff)),
        asserta(armorEquipped(none)),
        asserta(accessoryEquipped(none)),
        write('Your Job is Sorcerer'), 
        inputStats(sorcerer), !.
assignJob(InputJob) :- 
        InputJob = 3, 
        retractall(job(_)),
        asserta(job(archer)), 
        asserta(usedSpace(0)),
        asserta(isOnQuest(0)),
        asserta(jmlGoblin(0)),
        asserta(jmlSlime(0)),
        asserta(jmlWolf(0)),
        asserta(jmlWitch(0)),
        asserta(jmlArmoredGoblin(0)),
        asserta(jmlCubicSlime(0)),
        asserta(jmlWerewolf(0)),
        asserta(jmlOgre(0)),
        asserta(jmlCursedKnight(0)),
        asserta(jmlUltimaDragon(0)),
        asserta(rewardExp(0)),
        asserta(rewardGold(0)),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        storeItem(medicine),
        asserta(weaponEquipped(woodenbow)),
        asserta(armorEquipped(none)),
        asserta(accessoryEquipped(none)),
        write('Your Job is Archer'), 
        inputStats(archer), !.
assignJob(_) :- write('Wrong input'),!.

inputStats(JobName) :- 
        JobName = swordsman,
        asserta(att(55)), 
        asserta(specialatt(85,3)),
        asserta(def(35)), 
        asserta(currHP(80)), 
        asserta(maxHP(80)), 
        asserta(gold(100)), 
        asserta(lvl(1)), 
        asserta(expr(0)).
inputStats(JobName) :- 
        JobName = sorcerer, 
        asserta(att(60)), 
        asserta(specialatt(100,3)),
        asserta(def(30)), 
        asserta(currHP(75)), 
        asserta(maxHP(75)), 
        asserta(gold(100)), 
        asserta(lvl(1)), 
        asserta(expr(0)).
inputStats(JobName) :- 
        JobName = archer, 
        asserta(att(60)), 
        asserta(specialatt(100,3)),
        asserta(def(30)), 
        asserta(currHP(80)), 
        asserta(maxHP(80)), 
        asserta(gold(100)),
        asserta(lvl(1)), 
        asserta(expr(0)).

levelUp :-
        expr(Exp),
        lvl(Lvl),
        ReqExp is Lvl*100,
        Exp < ReqExp,
        !.
levelUp :-
        expr(Exp),
        lvl(Lvl),
        ReqExp is Lvl*100,
        Exp >= ReqExp,
        NewLevel is Lvl+1,
        NewExp is Exp-ReqExp,
        inputStatsLvlUp,
        retract(lvl(_)),
        asserta(lvl(NewLevel)),
        retract(expr(_)),
        asserta(expr(NewExp)),
        write('You leveled up! You are now level '),
        write(NewLevel),
        nl,
        levelUp,
        !.

inputStatsLvlUp :-
        job(JobName),
        JobName = swordsman,
        att(Att),
        specialatt(SpAtt,_),
        def(Def),
        maxHP(MaxHP),
        NewAtt is Att+5,
        NewSpAtt is SpAtt+4,
        NewDef is Def+10,
        NewMaxHP is MaxHP+50,
        retract(att(_)),
        asserta(att(NewAtt)),
        retract(specialatt(_,_)),
        asserta(specialatt(NewSpAtt,_)),
        retract(def(_)),
        asserta(def(NewDef)),
        retract(maxHP(_)),
        asserta(maxHP(NewMaxHP)),
        retract(currHP(_)),
        asserta(currHP(NewMaxHP)).
inputStatsLvlUp :-
        job(JobName),
        JobName = sorcerer,
        att(Att),
        specialatt(SpAtt,_),
        def(Def),
        maxHP(MaxHP),
        NewAtt is Att+8,
        NewSpAtt is SpAtt+20,
        NewDef is Def+5,
        NewMaxHP is MaxHP+50,
        retract(att(_)),
        asserta(att(NewAtt)),
        retract(specialatt(_,_)),
        asserta(specialatt(NewSpAtt,_)),
        retract(def(_)),
        asserta(def(NewDef)),
        retract(maxHP(_)),
        asserta(maxHP(NewMaxHP)),
        retract(currHP(_)),
        asserta(currHP(NewMaxHP)).
inputStatsLvlUp :-
        job(JobName),
        JobName = archer,
        att(Att),
        specialatt(SpAtt,_),
        def(Def),
        maxHP(MaxHP),
        NewAtt is Att+15,
        NewSpAtt is SpAtt+5,
        NewDef is Def+3,
        NewMaxHP is MaxHP+50,
        retract(att(_)),
        asserta(att(NewAtt)),
        retract(specialatt(_,_)),
        asserta(specialatt(NewSpAtt,_)),
        retract(def(_)),
        asserta(def(NewDef)),
        retract(maxHP(_)),
        asserta(maxHP(NewMaxHP)),
        retract(currHP(_)),
        asserta(currHP(NewMaxHP)).

stats :-
        job(JobName), 
        write('Job: '), 
        write(JobName), nl,
        currHP(CurrentHP), 
        maxHP(MaxHP), 
        write('Health: '), 
        write(CurrentHP), 
        write('/'), 
        write(MaxHP), nl,
        att(Attack), 
        write('Attack: '), 
        write(Attack), nl,
        specialatt(SpAtt,_),
        write('Special Attack: '), 
        write(SpAtt), nl,
        def(Defense), 
        write('Defense: '), 
        write(Defense), nl,
        lvl(Lvl),
        write('Level: '),
        write(Lvl), nl,
        expr(Exp), 
        write('Exp: '), 
        write(Exp), nl,
        gold(Gold), 
        write('Gold: '), 
        write(Gold), !.
