savegame :- write('Masukkan nama file untuk menyimpan permainan : '), read(FileName), nl,
            open(FileName,write,Savedata),
            position(player,X,Y),
            job(JobName), 
            maxHP(MaxHP),
            currHP(CurrentHP),  
            att(Attack),
            specialatt(SpecialAttack,_),
            def(Defense), 
            lvl(Level),
            expr(Exp), 
            gold(Gold),
            weaponEquipped(Weapon),
            armorEquipped(Armor),
            accessoryEquipped(Accessory),
            write(Savedata,X),          write(Savedata,'.'),nl(Savedata),
            write(Savedata,Y),          write(Savedata,'.'),nl(Savedata),
            write(Savedata,JobName),	write(Savedata,'.'),nl(Savedata),
            write(Savedata,MaxHP),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,CurrentHP),	write(Savedata,'.'),nl(Savedata),
            write(Savedata,Attack),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,SpecialAttack),write(Savedata,'.'),nl(Savedata),
            write(Savedata,Defense),	write(Savedata,'.'),nl(Savedata),
            write(Savedata,Level),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,Exp),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,Gold),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,Weapon),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,Armor),	    write(Savedata,'.'),nl(Savedata),
            write(Savedata,Accessory),	write(Savedata,'.'),nl(Savedata),
            close(Savedata),
            atom_concat(FileName, '_inventory', SaveInventoryName),
            open(SaveInventoryName,write,SavedataInventory),
            inventory(UsedSpace),
            write(SavedataInventory,'usedSpace('), write(SavedataInventory,UsedSpace),	write(SavedataInventory,')'), write(SavedataInventory,'.'),nl(SavedataInventory),
            forall((isInInventory(Item)), (countItemInventory(Item, CountItem), write(SavedataInventory,'stored('), write(SavedataInventory,Item), write(SavedataInventory,','),
            write(SavedataInventory,CountItem), write(SavedataInventory,')'), write(SavedataInventory,'.'),nl(SavedataInventory))), nl,
            write('Data sudah tersimpan!'),nl,
            close(SavedataInventory).

loadgame :- write('Masukkan nama file untuk memuat data permainan : '), read(FileName), nl,
            open(FileName,read,Savedata),
            startstate(State),
            State is 0,

            read(Savedata,NewX),
            read(Savedata,NewY),
            read(Savedata,NewJobName),
            read(Savedata,NewMaxHP),
            read(Savedata,NewCurrentHP),
            read(Savedata,NewAttack),
            read(Savedata,NewSpecialAttack),
            read(Savedata,NewDefense),
            read(Savedata,NewLevel),
            read(Savedata,NewExp),
            read(Savedata,NewGold),
            read(Savedata,NewWeapon),
            read(Savedata,NewArmor),
            read(Savedata,NewAccessory),

            write('membaca save data berhasil...'),nl,

            retract(startstate(_)),
            asserta(startstate(1)),

            retractall(job(_)),
            asserta(job(NewJobName)),
            asserta(usedSpace(0)),
            asserta(isOnQuest(0)),
            asserta(jmlGoblin(0)),
            asserta(jmlSlime(0)),
            asserta(jmlWolf(0)),
            asserta(jmlWitch(0)),
            asserta(jmlArmoredGoblin(0)),
            asserta(jmlCubicSlime(0)),
            asserta(jmlWerewolf(0)),
            asserta(jmlOgre(0)),
            asserta(jmlCursedKnight(0)),
            asserta(jmlUltimaDragon(0)),
            asserta(rewardExp(0)),
            asserta(rewardGold(0)),
            asserta(weaponEquipped(NewWeapon)),
            asserta(armorEquipped(NewArmor)),
            asserta(accessoryEquipped(NewAccessory)),
            asserta(maxHP(NewMaxHP)),
            asserta(currHP(NewCurrentHP)),
            asserta(att(NewAttack)),
            asserta(specialatt(NewSpecialAttack,3)),
            asserta(def(NewDefense)),
            asserta(gold(NewGold)),
            asserta(lvl(NewLevel)), 
            asserta(expr(NewExp)),
            initmap(M),
            position(player,X,Y),
            replace_elmt('_',M,M1,X+1,Y+1),
            replace_elmt('P',M1,M2,NewX+1,NewY+1),
            retract(initmap(_)),
            asserta(initmap(M2)),
            retract(position(player,_,_)),
            asserta(position(player,NewX,NewY)),
            close(Savedata),

            atom_concat(FileName, '_inventory', SaveInventoryName),
            open(SaveInventoryName,read,LoadInventory),
            load_all(LoadInventory),
            close(LoadInventory),
            write('Load save data berhasil!'),nl,!.

load_all(Load) :-
	repeat,
		read(Load,L),
		asserta(L),
		at_end_of_stream(Load).